### ISSUE TITLE
Any chance of windows version?

### ISSUE THREAD

**Issue by gfmoore** [loics2/node-mplayer#10]
OOPS, just noticed your Not being developed notice.

However, yourlink to the node  mplayer  has saved the day! :)  

----------------
I have spent many, many hours trying to find a node implementation of an audio player.

I'm guessing there is some fundamental reason why this isn't being done.

So, more in hope than expectation was just wondering if you had any plans?

I know I can run mplayer by exec or childprocess or some such (same as I can for mpg123), but having the play, pause, stop, mute and volume controls is tricky - aka I don't know how :(

:)

Gordon

**Comment by loics2** [comment]
No problem!

All these modules use the mplayer slave mode and Node's `child_process` API, so it shouldn't depend on the OS.

Good luck!
