### ISSUE TITLE
setPlayList

### ISSUE THREAD

**Issue by sergionader** [loics2/node-mplayer#2]
Hello!

Do you have plans to implement a setPlayList method?

It would be nice to have to ability to use node-mplayer to play radio stations.

Regards, 

Sergio

**Comment by loics2** [comment]
Nice proposition ! I'll work on that.

Loïc

**Comment by nitishm** [comment]
Any updates on this ? I would like if we could play .pls extention files.

**Comment by loics2** [comment]
I have time to work on this again, I'll implement the *.pls file reading asap, it shouldn't be too long.

**Comment by loics2** [comment]
[This module](https://github.com/noodny/mplayer) provides the *.pls usage and much more, I suggest that you use it instead
