### ISSUE TITLE
volume argument on spawn

### ISSUE THREAD

**Issue by atakanyenel** [loics2/node-mplayer#7]
I couldn't hear any sound with the --volume= argument, so I changed it to ' -volume ' ,but still couldn't get any sound. 

When I removed the argument it worked as expected.

**Comment by atakanyenel** [comment]
I made a fix on it by setting the volume after starting the song. You can see it from the [fork.](https://github.com/atayenel/node-mplayer)

**Comment by loics2** [comment]
Hey thanks! Can you tell me what version of mplayer and node do you have?

**Comment by atakanyenel** [comment]
node is 5.8.0  and Mplayer 1.1-4.8 . I ran the mplayer with your arguments and it says 

```
Unknown option on the command line: --volume=100
Error parsing option on the command line: --volume=100
MPlayer 1.1-4.8 (C) 2000-2012 MPlayer Team
```

**Comment by loics2** [comment]
Hmm I always worked with MPlayer2, but apparently the development has stopped. 

I'll update the module to work with MPlayer 1.3.x (the FFMPEG 3 version), and 1.2.x (FFMPEG 2). With these versions, the `--volume` parameter doesn't work. But you should maybe upgrade your MPlayer version to one of those.

Thanks for reporting this!
