### ISSUE TITLE
Get streamtitle and file info

### ISSUE THREAD

**Issue by nitishm** [loics2/node-mplayer#8]
It would also be nice to collect the **streamTitle** info when playing radio streams. Additionally when playing local files it would help if the **artist/album/genre** information could be collected from the following stdout output : 

```
mp3 @ 0x75b225b8]Estimating duration from bitrate, this may be inaccurate
[lavf] stream 0: audio (mp3), -aid 0
[lavf] stream 1: video (mjpeg), -vid 0, 

Clip info:
 Release date: Songspk.LINK
 album_artist: Various Artists
 album: Kapoor & Sons (Since 1921)
 artist: Tanishk Bagchi, Arijit Singh & Asees Kaur

 composer: Amaal Mallik | Songspk.LINK
 disc: 1/1
 encoded_by: Lame
 genre: Bollywood Music
 title: Bolna - Songspk.LINK
 track: 1/1
 EpisodeID: Songspk.LINK
 copyright: Songspk.LINK
 TOPE: Amaal Mallik | Songspk.LINK
 TIT1: Songspk.LINK
 TIT3: Songspk.LINK
```

I have implemented this partially to collect streamtitle from radio streams and also song title for local files.

**Comment by loics2** [comment]
Like I said in another issue, [this module](https://github.com/noodny/mplayer) handles streams and playlists way better. I suggest you use it instead.

**Comment by nitishm** [comment]
Yup I am aware of that module. Just thought it would be a good addition to your module as well since I feel it is much more readable IMO.

Thanks anyway.
